//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_xmcml.ServiceReferenceMCMLViewer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDouble", Namespace="WEB-xmcml", ItemName="double")]
    [System.SerializableAttribute()]
    public class ArrayOfDouble : System.Collections.Generic.List<double> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WEB-xmcml", ConfigurationName="ServiceReferenceMCMLViewer.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name GetModeResult from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetMode", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetModeResponse GetMode(WEB_xmcml.ServiceReferenceMCMLViewer.GetModeRequest request);
        
        // CODEGEN: Generating message contract since element name ID_MCML from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/OpenMCML", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceMCMLViewer.OpenMCMLResponse OpenMCML(WEB_xmcml.ServiceReferenceMCMLViewer.OpenMCMLRequest request);
        
        // CODEGEN: Generating message contract since element name GetInfoMCMLResult from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetInfoMCML", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoMCMLResponse GetInfoMCML(WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoMCMLRequest request);
        
        // CODEGEN: Generating message contract since element name KEY_SESSION from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/InitFiles", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceMCMLViewer.InitFilesResponse InitFiles(WEB_xmcml.ServiceReferenceMCMLViewer.InitFilesRequest request);
        
        // CODEGEN: Generating message contract since element name KEY_SESSION from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetNameImageLogo", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetNameImageLogoResponse GetNameImageLogo(WEB_xmcml.ServiceReferenceMCMLViewer.GetNameImageLogoRequest request);
        
        // CODEGEN: Generating message contract since element name KEY_SESSION from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetPathImageOriginal", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetPathImageOriginalResponse GetPathImageOriginal(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathImageOriginalRequest request);
        
        // CODEGEN: Generating message contract since element name KEY_SESSION from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetPathMatrix", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetPathMatrixResponse GetPathMatrix(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathMatrixRequest request);
        
        // CODEGEN: Generating message contract since element name KEY_SESSION from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetPathTimeScales", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetPathTimeScalesResponse GetPathTimeScales(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathTimeScalesRequest request);
        
        // CODEGEN: Generating message contract since element name KEY_SESSION from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetPathAllAsText", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetPathAllAsTextResponse GetPathAllAsText(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathAllAsTextRequest request);
        
        // CODEGEN: Generating message contract since element name KEY_SESSION from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetPathWeights", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetPathWeightsResponse GetPathWeights(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathWeightsRequest request);
        
        // CODEGEN: Generating message contract since element name KEY_SESSION from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetPathRanges", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetPathRangesResponse GetPathRanges(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathRangesRequest request);
        
        // CODEGEN: Generating message contract since element name type from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetInfoOfArea", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoOfAreaResponse GetInfoOfArea(WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoOfAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetNumberOfDetectors", ReplyAction="*")]
        int GetNumberOfDetectors();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMode", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetModeRequestBody Body;
        
        public GetModeRequest() {
        }
        
        public GetModeRequest(WEB_xmcml.ServiceReferenceMCMLViewer.GetModeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetModeRequestBody {
        
        public GetModeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetModeResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetModeResponseBody Body;
        
        public GetModeResponse() {
        }
        
        public GetModeResponse(WEB_xmcml.ServiceReferenceMCMLViewer.GetModeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetModeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetModeResult;
        
        public GetModeResponseBody() {
        }
        
        public GetModeResponseBody(string GetModeResult) {
            this.GetModeResult = GetModeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenMCMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenMCML", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.OpenMCMLRequestBody Body;
        
        public OpenMCMLRequest() {
        }
        
        public OpenMCMLRequest(WEB_xmcml.ServiceReferenceMCMLViewer.OpenMCMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class OpenMCMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID_MCML;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int MODE_OPEN;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int detectorID;
        
        public OpenMCMLRequestBody() {
        }
        
        public OpenMCMLRequestBody(string ID_MCML, int MODE_OPEN, int detectorID) {
            this.ID_MCML = ID_MCML;
            this.MODE_OPEN = MODE_OPEN;
            this.detectorID = detectorID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenMCMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenMCMLResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.OpenMCMLResponseBody Body;
        
        public OpenMCMLResponse() {
        }
        
        public OpenMCMLResponse(WEB_xmcml.ServiceReferenceMCMLViewer.OpenMCMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class OpenMCMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool OpenMCMLResult;
        
        public OpenMCMLResponseBody() {
        }
        
        public OpenMCMLResponseBody(bool OpenMCMLResult) {
            this.OpenMCMLResult = OpenMCMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoMCMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoMCML", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoMCMLRequestBody Body;
        
        public GetInfoMCMLRequest() {
        }
        
        public GetInfoMCMLRequest(WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoMCMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInfoMCMLRequestBody {
        
        public GetInfoMCMLRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoMCMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoMCMLResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoMCMLResponseBody Body;
        
        public GetInfoMCMLResponse() {
        }
        
        public GetInfoMCMLResponse(WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoMCMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetInfoMCMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoMCMLResult;
        
        public GetInfoMCMLResponseBody() {
        }
        
        public GetInfoMCMLResponseBody(string GetInfoMCMLResult) {
            this.GetInfoMCMLResult = GetInfoMCMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InitFiles", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.InitFilesRequestBody Body;
        
        public InitFilesRequest() {
        }
        
        public InitFilesRequest(WEB_xmcml.ServiceReferenceMCMLViewer.InitFilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class InitFilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KEY_SESSION;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double width;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double height;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double var;
        
        public InitFilesRequestBody() {
        }
        
        public InitFilesRequestBody(string KEY_SESSION, double width, double height, string type, double var) {
            this.KEY_SESSION = KEY_SESSION;
            this.width = width;
            this.height = height;
            this.type = type;
            this.var = var;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InitFilesResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.InitFilesResponseBody Body;
        
        public InitFilesResponse() {
        }
        
        public InitFilesResponse(WEB_xmcml.ServiceReferenceMCMLViewer.InitFilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class InitFilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InitFilesResult;
        
        public InitFilesResponseBody() {
        }
        
        public InitFilesResponseBody(bool InitFilesResult) {
            this.InitFilesResult = InitFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNameImageLogoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNameImageLogo", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetNameImageLogoRequestBody Body;
        
        public GetNameImageLogoRequest() {
        }
        
        public GetNameImageLogoRequest(WEB_xmcml.ServiceReferenceMCMLViewer.GetNameImageLogoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetNameImageLogoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KEY_SESSION;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        public GetNameImageLogoRequestBody() {
        }
        
        public GetNameImageLogoRequestBody(string KEY_SESSION, string type) {
            this.KEY_SESSION = KEY_SESSION;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNameImageLogoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNameImageLogoResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetNameImageLogoResponseBody Body;
        
        public GetNameImageLogoResponse() {
        }
        
        public GetNameImageLogoResponse(WEB_xmcml.ServiceReferenceMCMLViewer.GetNameImageLogoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetNameImageLogoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNameImageLogoResult;
        
        public GetNameImageLogoResponseBody() {
        }
        
        public GetNameImageLogoResponseBody(string GetNameImageLogoResult) {
            this.GetNameImageLogoResult = GetNameImageLogoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathImageOriginalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathImageOriginal", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetPathImageOriginalRequestBody Body;
        
        public GetPathImageOriginalRequest() {
        }
        
        public GetPathImageOriginalRequest(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathImageOriginalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathImageOriginalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KEY_SESSION;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        public GetPathImageOriginalRequestBody() {
        }
        
        public GetPathImageOriginalRequestBody(string KEY_SESSION, string type) {
            this.KEY_SESSION = KEY_SESSION;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathImageOriginalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathImageOriginalResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetPathImageOriginalResponseBody Body;
        
        public GetPathImageOriginalResponse() {
        }
        
        public GetPathImageOriginalResponse(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathImageOriginalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathImageOriginalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPathImageOriginalResult;
        
        public GetPathImageOriginalResponseBody() {
        }
        
        public GetPathImageOriginalResponseBody(string GetPathImageOriginalResult) {
            this.GetPathImageOriginalResult = GetPathImageOriginalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathMatrixRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathMatrix", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetPathMatrixRequestBody Body;
        
        public GetPathMatrixRequest() {
        }
        
        public GetPathMatrixRequest(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathMatrixRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathMatrixRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KEY_SESSION;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        public GetPathMatrixRequestBody() {
        }
        
        public GetPathMatrixRequestBody(string KEY_SESSION, string type) {
            this.KEY_SESSION = KEY_SESSION;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathMatrixResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathMatrixResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetPathMatrixResponseBody Body;
        
        public GetPathMatrixResponse() {
        }
        
        public GetPathMatrixResponse(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathMatrixResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathMatrixResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPathMatrixResult;
        
        public GetPathMatrixResponseBody() {
        }
        
        public GetPathMatrixResponseBody(string GetPathMatrixResult) {
            this.GetPathMatrixResult = GetPathMatrixResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathTimeScalesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathTimeScales", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetPathTimeScalesRequestBody Body;
        
        public GetPathTimeScalesRequest() {
        }
        
        public GetPathTimeScalesRequest(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathTimeScalesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathTimeScalesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KEY_SESSION;
        
        public GetPathTimeScalesRequestBody() {
        }
        
        public GetPathTimeScalesRequestBody(string KEY_SESSION) {
            this.KEY_SESSION = KEY_SESSION;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathTimeScalesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathTimeScalesResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetPathTimeScalesResponseBody Body;
        
        public GetPathTimeScalesResponse() {
        }
        
        public GetPathTimeScalesResponse(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathTimeScalesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathTimeScalesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPathTimeScalesResult;
        
        public GetPathTimeScalesResponseBody() {
        }
        
        public GetPathTimeScalesResponseBody(string GetPathTimeScalesResult) {
            this.GetPathTimeScalesResult = GetPathTimeScalesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathAllAsTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathAllAsText", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetPathAllAsTextRequestBody Body;
        
        public GetPathAllAsTextRequest() {
        }
        
        public GetPathAllAsTextRequest(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathAllAsTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathAllAsTextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KEY_SESSION;
        
        public GetPathAllAsTextRequestBody() {
        }
        
        public GetPathAllAsTextRequestBody(string KEY_SESSION) {
            this.KEY_SESSION = KEY_SESSION;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathAllAsTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathAllAsTextResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetPathAllAsTextResponseBody Body;
        
        public GetPathAllAsTextResponse() {
        }
        
        public GetPathAllAsTextResponse(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathAllAsTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathAllAsTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPathAllAsTextResult;
        
        public GetPathAllAsTextResponseBody() {
        }
        
        public GetPathAllAsTextResponseBody(string GetPathAllAsTextResult) {
            this.GetPathAllAsTextResult = GetPathAllAsTextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathWeightsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathWeights", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetPathWeightsRequestBody Body;
        
        public GetPathWeightsRequest() {
        }
        
        public GetPathWeightsRequest(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathWeightsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathWeightsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KEY_SESSION;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int mode;
        
        public GetPathWeightsRequestBody() {
        }
        
        public GetPathWeightsRequestBody(string KEY_SESSION, int mode) {
            this.KEY_SESSION = KEY_SESSION;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathWeightsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathWeightsResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetPathWeightsResponseBody Body;
        
        public GetPathWeightsResponse() {
        }
        
        public GetPathWeightsResponse(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathWeightsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathWeightsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPathWeightsResult;
        
        public GetPathWeightsResponseBody() {
        }
        
        public GetPathWeightsResponseBody(string GetPathWeightsResult) {
            this.GetPathWeightsResult = GetPathWeightsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathRangesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathRanges", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetPathRangesRequestBody Body;
        
        public GetPathRangesRequest() {
        }
        
        public GetPathRangesRequest(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathRangesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathRangesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KEY_SESSION;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int mode;
        
        public GetPathRangesRequestBody() {
        }
        
        public GetPathRangesRequestBody(string KEY_SESSION, int mode) {
            this.KEY_SESSION = KEY_SESSION;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathRangesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathRangesResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetPathRangesResponseBody Body;
        
        public GetPathRangesResponse() {
        }
        
        public GetPathRangesResponse(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathRangesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathRangesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPathRangesResult;
        
        public GetPathRangesResponseBody() {
        }
        
        public GetPathRangesResponseBody(string GetPathRangesResult) {
            this.GetPathRangesResult = GetPathRangesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoOfAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoOfArea", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoOfAreaRequestBody Body;
        
        public GetInfoOfAreaRequest() {
        }
        
        public GetInfoOfAreaRequest(WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoOfAreaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetInfoOfAreaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string type;
        
        public GetInfoOfAreaRequestBody() {
        }
        
        public GetInfoOfAreaRequestBody(string type) {
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoOfAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoOfAreaResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoOfAreaResponseBody Body;
        
        public GetInfoOfAreaResponse() {
        }
        
        public GetInfoOfAreaResponse(WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoOfAreaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetInfoOfAreaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WEB_xmcml.ServiceReferenceMCMLViewer.ArrayOfDouble GetInfoOfAreaResult;
        
        public GetInfoOfAreaResponseBody() {
        }
        
        public GetInfoOfAreaResponseBody(WEB_xmcml.ServiceReferenceMCMLViewer.ArrayOfDouble GetInfoOfAreaResult) {
            this.GetInfoOfAreaResult = GetInfoOfAreaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap>, WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetModeResponse WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap.GetMode(WEB_xmcml.ServiceReferenceMCMLViewer.GetModeRequest request) {
            return base.Channel.GetMode(request);
        }
        
        public string GetMode() {
            WEB_xmcml.ServiceReferenceMCMLViewer.GetModeRequest inValue = new WEB_xmcml.ServiceReferenceMCMLViewer.GetModeRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceMCMLViewer.GetModeRequestBody();
            WEB_xmcml.ServiceReferenceMCMLViewer.GetModeResponse retVal = ((WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap)(this)).GetMode(inValue);
            return retVal.Body.GetModeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceMCMLViewer.OpenMCMLResponse WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap.OpenMCML(WEB_xmcml.ServiceReferenceMCMLViewer.OpenMCMLRequest request) {
            return base.Channel.OpenMCML(request);
        }
        
        public bool OpenMCML(string ID_MCML, int MODE_OPEN, int detectorID) {
            WEB_xmcml.ServiceReferenceMCMLViewer.OpenMCMLRequest inValue = new WEB_xmcml.ServiceReferenceMCMLViewer.OpenMCMLRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceMCMLViewer.OpenMCMLRequestBody();
            inValue.Body.ID_MCML = ID_MCML;
            inValue.Body.MODE_OPEN = MODE_OPEN;
            inValue.Body.detectorID = detectorID;
            WEB_xmcml.ServiceReferenceMCMLViewer.OpenMCMLResponse retVal = ((WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap)(this)).OpenMCML(inValue);
            return retVal.Body.OpenMCMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoMCMLResponse WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap.GetInfoMCML(WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoMCMLRequest request) {
            return base.Channel.GetInfoMCML(request);
        }
        
        public string GetInfoMCML() {
            WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoMCMLRequest inValue = new WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoMCMLRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoMCMLRequestBody();
            WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoMCMLResponse retVal = ((WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap)(this)).GetInfoMCML(inValue);
            return retVal.Body.GetInfoMCMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceMCMLViewer.InitFilesResponse WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap.InitFiles(WEB_xmcml.ServiceReferenceMCMLViewer.InitFilesRequest request) {
            return base.Channel.InitFiles(request);
        }
        
        public bool InitFiles(string KEY_SESSION, double width, double height, string type, double var) {
            WEB_xmcml.ServiceReferenceMCMLViewer.InitFilesRequest inValue = new WEB_xmcml.ServiceReferenceMCMLViewer.InitFilesRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceMCMLViewer.InitFilesRequestBody();
            inValue.Body.KEY_SESSION = KEY_SESSION;
            inValue.Body.width = width;
            inValue.Body.height = height;
            inValue.Body.type = type;
            inValue.Body.var = var;
            WEB_xmcml.ServiceReferenceMCMLViewer.InitFilesResponse retVal = ((WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap)(this)).InitFiles(inValue);
            return retVal.Body.InitFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetNameImageLogoResponse WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap.GetNameImageLogo(WEB_xmcml.ServiceReferenceMCMLViewer.GetNameImageLogoRequest request) {
            return base.Channel.GetNameImageLogo(request);
        }
        
        public string GetNameImageLogo(string KEY_SESSION, string type) {
            WEB_xmcml.ServiceReferenceMCMLViewer.GetNameImageLogoRequest inValue = new WEB_xmcml.ServiceReferenceMCMLViewer.GetNameImageLogoRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceMCMLViewer.GetNameImageLogoRequestBody();
            inValue.Body.KEY_SESSION = KEY_SESSION;
            inValue.Body.type = type;
            WEB_xmcml.ServiceReferenceMCMLViewer.GetNameImageLogoResponse retVal = ((WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap)(this)).GetNameImageLogo(inValue);
            return retVal.Body.GetNameImageLogoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetPathImageOriginalResponse WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap.GetPathImageOriginal(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathImageOriginalRequest request) {
            return base.Channel.GetPathImageOriginal(request);
        }
        
        public string GetPathImageOriginal(string KEY_SESSION, string type) {
            WEB_xmcml.ServiceReferenceMCMLViewer.GetPathImageOriginalRequest inValue = new WEB_xmcml.ServiceReferenceMCMLViewer.GetPathImageOriginalRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceMCMLViewer.GetPathImageOriginalRequestBody();
            inValue.Body.KEY_SESSION = KEY_SESSION;
            inValue.Body.type = type;
            WEB_xmcml.ServiceReferenceMCMLViewer.GetPathImageOriginalResponse retVal = ((WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap)(this)).GetPathImageOriginal(inValue);
            return retVal.Body.GetPathImageOriginalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetPathMatrixResponse WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap.GetPathMatrix(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathMatrixRequest request) {
            return base.Channel.GetPathMatrix(request);
        }
        
        public string GetPathMatrix(string KEY_SESSION, string type) {
            WEB_xmcml.ServiceReferenceMCMLViewer.GetPathMatrixRequest inValue = new WEB_xmcml.ServiceReferenceMCMLViewer.GetPathMatrixRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceMCMLViewer.GetPathMatrixRequestBody();
            inValue.Body.KEY_SESSION = KEY_SESSION;
            inValue.Body.type = type;
            WEB_xmcml.ServiceReferenceMCMLViewer.GetPathMatrixResponse retVal = ((WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap)(this)).GetPathMatrix(inValue);
            return retVal.Body.GetPathMatrixResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetPathTimeScalesResponse WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap.GetPathTimeScales(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathTimeScalesRequest request) {
            return base.Channel.GetPathTimeScales(request);
        }
        
        public string GetPathTimeScales(string KEY_SESSION) {
            WEB_xmcml.ServiceReferenceMCMLViewer.GetPathTimeScalesRequest inValue = new WEB_xmcml.ServiceReferenceMCMLViewer.GetPathTimeScalesRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceMCMLViewer.GetPathTimeScalesRequestBody();
            inValue.Body.KEY_SESSION = KEY_SESSION;
            WEB_xmcml.ServiceReferenceMCMLViewer.GetPathTimeScalesResponse retVal = ((WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap)(this)).GetPathTimeScales(inValue);
            return retVal.Body.GetPathTimeScalesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetPathAllAsTextResponse WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap.GetPathAllAsText(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathAllAsTextRequest request) {
            return base.Channel.GetPathAllAsText(request);
        }
        
        public string GetPathAllAsText(string KEY_SESSION) {
            WEB_xmcml.ServiceReferenceMCMLViewer.GetPathAllAsTextRequest inValue = new WEB_xmcml.ServiceReferenceMCMLViewer.GetPathAllAsTextRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceMCMLViewer.GetPathAllAsTextRequestBody();
            inValue.Body.KEY_SESSION = KEY_SESSION;
            WEB_xmcml.ServiceReferenceMCMLViewer.GetPathAllAsTextResponse retVal = ((WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap)(this)).GetPathAllAsText(inValue);
            return retVal.Body.GetPathAllAsTextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetPathWeightsResponse WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap.GetPathWeights(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathWeightsRequest request) {
            return base.Channel.GetPathWeights(request);
        }
        
        public string GetPathWeights(string KEY_SESSION, int mode) {
            WEB_xmcml.ServiceReferenceMCMLViewer.GetPathWeightsRequest inValue = new WEB_xmcml.ServiceReferenceMCMLViewer.GetPathWeightsRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceMCMLViewer.GetPathWeightsRequestBody();
            inValue.Body.KEY_SESSION = KEY_SESSION;
            inValue.Body.mode = mode;
            WEB_xmcml.ServiceReferenceMCMLViewer.GetPathWeightsResponse retVal = ((WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap)(this)).GetPathWeights(inValue);
            return retVal.Body.GetPathWeightsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetPathRangesResponse WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap.GetPathRanges(WEB_xmcml.ServiceReferenceMCMLViewer.GetPathRangesRequest request) {
            return base.Channel.GetPathRanges(request);
        }
        
        public string GetPathRanges(string KEY_SESSION, int mode) {
            WEB_xmcml.ServiceReferenceMCMLViewer.GetPathRangesRequest inValue = new WEB_xmcml.ServiceReferenceMCMLViewer.GetPathRangesRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceMCMLViewer.GetPathRangesRequestBody();
            inValue.Body.KEY_SESSION = KEY_SESSION;
            inValue.Body.mode = mode;
            WEB_xmcml.ServiceReferenceMCMLViewer.GetPathRangesResponse retVal = ((WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap)(this)).GetPathRanges(inValue);
            return retVal.Body.GetPathRangesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoOfAreaResponse WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap.GetInfoOfArea(WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoOfAreaRequest request) {
            return base.Channel.GetInfoOfArea(request);
        }
        
        public WEB_xmcml.ServiceReferenceMCMLViewer.ArrayOfDouble GetInfoOfArea(string type) {
            WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoOfAreaRequest inValue = new WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoOfAreaRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoOfAreaRequestBody();
            inValue.Body.type = type;
            WEB_xmcml.ServiceReferenceMCMLViewer.GetInfoOfAreaResponse retVal = ((WEB_xmcml.ServiceReferenceMCMLViewer.Service1Soap)(this)).GetInfoOfArea(inValue);
            return retVal.Body.GetInfoOfAreaResult;
        }
        
        public int GetNumberOfDetectors() {
            return base.Channel.GetNumberOfDetectors();
        }
    }
}
