//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_xmcml.ServiceReferenceXMLCreator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="WEB-xmcml", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WEB-xmcml", ConfigurationName="ServiceReferenceXMLCreator.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name numberOfPhotons from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetXML", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceXMLCreator.GetXMLResponse GetXML(WEB_xmcml.ServiceReferenceXMLCreator.GetXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXML", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceXMLCreator.GetXMLRequestBody Body;
        
        public GetXMLRequest() {
        }
        
        public GetXMLRequest(WEB_xmcml.ServiceReferenceXMLCreator.GetXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numberOfPhotons;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string minWeight;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString corner;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString length;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString partition;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int numLayers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString refractiveIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString absorptionCoefficient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString scatteringCoefficient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString anisotropy;
        
        public GetXMLRequestBody() {
        }
        
        public GetXMLRequestBody(string numberOfPhotons, string minWeight, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString corner, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString length, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString partition, int numLayers, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString refractiveIndex, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString absorptionCoefficient, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString scatteringCoefficient, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString anisotropy) {
            this.numberOfPhotons = numberOfPhotons;
            this.minWeight = minWeight;
            this.corner = corner;
            this.length = length;
            this.partition = partition;
            this.numLayers = numLayers;
            this.refractiveIndex = refractiveIndex;
            this.absorptionCoefficient = absorptionCoefficient;
            this.scatteringCoefficient = scatteringCoefficient;
            this.anisotropy = anisotropy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXMLResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceXMLCreator.GetXMLResponseBody Body;
        
        public GetXMLResponse() {
        }
        
        public GetXMLResponse(WEB_xmcml.ServiceReferenceXMLCreator.GetXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetXMLResult;
        
        public GetXMLResponseBody() {
        }
        
        public GetXMLResponseBody(string GetXMLResult) {
            this.GetXMLResult = GetXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WEB_xmcml.ServiceReferenceXMLCreator.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WEB_xmcml.ServiceReferenceXMLCreator.Service1Soap>, WEB_xmcml.ServiceReferenceXMLCreator.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceXMLCreator.GetXMLResponse WEB_xmcml.ServiceReferenceXMLCreator.Service1Soap.GetXML(WEB_xmcml.ServiceReferenceXMLCreator.GetXMLRequest request) {
            return base.Channel.GetXML(request);
        }
        
        public string GetXML(string numberOfPhotons, string minWeight, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString corner, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString length, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString partition, int numLayers, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString refractiveIndex, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString absorptionCoefficient, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString scatteringCoefficient, WEB_xmcml.ServiceReferenceXMLCreator.ArrayOfString anisotropy) {
            WEB_xmcml.ServiceReferenceXMLCreator.GetXMLRequest inValue = new WEB_xmcml.ServiceReferenceXMLCreator.GetXMLRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceXMLCreator.GetXMLRequestBody();
            inValue.Body.numberOfPhotons = numberOfPhotons;
            inValue.Body.minWeight = minWeight;
            inValue.Body.corner = corner;
            inValue.Body.length = length;
            inValue.Body.partition = partition;
            inValue.Body.numLayers = numLayers;
            inValue.Body.refractiveIndex = refractiveIndex;
            inValue.Body.absorptionCoefficient = absorptionCoefficient;
            inValue.Body.scatteringCoefficient = scatteringCoefficient;
            inValue.Body.anisotropy = anisotropy;
            WEB_xmcml.ServiceReferenceXMLCreator.GetXMLResponse retVal = ((WEB_xmcml.ServiceReferenceXMLCreator.Service1Soap)(this)).GetXML(inValue);
            return retVal.Body.GetXMLResult;
        }
    }
}
