#ifndef __SECTIONS_H
#define __SECTIONS_H

#define MCML_SECTION_NUMBER_OF_PHOTONS     0x01
#define MCML_SECTION_AREA                  0x02
#define MCML_SECTION_CUBE_DETECTORS        0x03
#define MCML_SECTION_SPECULAR_REFLECTANCE  0x04
#define MCML_SECTION_COMMON_TRAJECTORIES   0x05
#define MCML_SECTION_SCATTERING_MAP	   0X06
#define MCML_SECTION_DETECTOR_WEIGHTS      0x07
#define MCML_SECTION_GRID_DETECTOR	   0x08
#define MCML_SECTION_DETECTOR_TRAJECTORIES 0x09
#define MCML_SECTION_DETECTOR_TIME_SCALE   0x0A
#define MCML_SECTION_RANDOM_GENERATOR      0x0B
#define MCML_SECTION_RING_DETECTORS        0x0C
#define MCML_SECTION_DETECTOR_RANGES       0x0D

#define MCML_SECTION_SURFACES              0x0100

#define MCML_SECTION_WEIGHT_INTEGRAL       0x0200

#endif //__SECTIONS_H
