//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_xmcml.ServiceReferenceLoadTasks {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WEB-xmcml", ConfigurationName="ServiceReferenceLoadTasks.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/Init", ReplyAction="*")]
        void Init();
        
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetCurrentID", ReplyAction="*")]
        int GetCurrentID();
        
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/ResetID", ReplyAction="*")]
        void ResetID();
        
        // CODEGEN: Generating message contract since element name taskName from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetIDNewTask", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceLoadTasks.GetIDNewTaskResponse GetIDNewTask(WEB_xmcml.ServiceReferenceLoadTasks.GetIDNewTaskRequest request);
        
        // CODEGEN: Generating message contract since element name GetPathXMLResult from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetPathXML", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceLoadTasks.GetPathXMLResponse GetPathXML(WEB_xmcml.ServiceReferenceLoadTasks.GetPathXMLRequest request);
        
        // CODEGEN: Generating message contract since element name GetPathSURFACEResult from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetPathSURFACE", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceLoadTasks.GetPathSURFACEResponse GetPathSURFACE(WEB_xmcml.ServiceReferenceLoadTasks.GetPathSURFACERequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIDNewTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIDNewTask", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceLoadTasks.GetIDNewTaskRequestBody Body;
        
        public GetIDNewTaskRequest() {
        }
        
        public GetIDNewTaskRequest(WEB_xmcml.ServiceReferenceLoadTasks.GetIDNewTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetIDNewTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string taskName;
        
        public GetIDNewTaskRequestBody() {
        }
        
        public GetIDNewTaskRequestBody(string taskName) {
            this.taskName = taskName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIDNewTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIDNewTaskResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceLoadTasks.GetIDNewTaskResponseBody Body;
        
        public GetIDNewTaskResponse() {
        }
        
        public GetIDNewTaskResponse(WEB_xmcml.ServiceReferenceLoadTasks.GetIDNewTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetIDNewTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetIDNewTaskResult;
        
        public GetIDNewTaskResponseBody() {
        }
        
        public GetIDNewTaskResponseBody(int GetIDNewTaskResult) {
            this.GetIDNewTaskResult = GetIDNewTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathXML", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceLoadTasks.GetPathXMLRequestBody Body;
        
        public GetPathXMLRequest() {
        }
        
        public GetPathXMLRequest(WEB_xmcml.ServiceReferenceLoadTasks.GetPathXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetPathXMLRequestBody() {
        }
        
        public GetPathXMLRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathXMLResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceLoadTasks.GetPathXMLResponseBody Body;
        
        public GetPathXMLResponse() {
        }
        
        public GetPathXMLResponse(WEB_xmcml.ServiceReferenceLoadTasks.GetPathXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPathXMLResult;
        
        public GetPathXMLResponseBody() {
        }
        
        public GetPathXMLResponseBody(string GetPathXMLResult) {
            this.GetPathXMLResult = GetPathXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathSURFACERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathSURFACE", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceLoadTasks.GetPathSURFACERequestBody Body;
        
        public GetPathSURFACERequest() {
        }
        
        public GetPathSURFACERequest(WEB_xmcml.ServiceReferenceLoadTasks.GetPathSURFACERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathSURFACERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetPathSURFACERequestBody() {
        }
        
        public GetPathSURFACERequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathSURFACEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathSURFACEResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceLoadTasks.GetPathSURFACEResponseBody Body;
        
        public GetPathSURFACEResponse() {
        }
        
        public GetPathSURFACEResponse(WEB_xmcml.ServiceReferenceLoadTasks.GetPathSURFACEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathSURFACEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPathSURFACEResult;
        
        public GetPathSURFACEResponseBody() {
        }
        
        public GetPathSURFACEResponseBody(string GetPathSURFACEResult) {
            this.GetPathSURFACEResult = GetPathSURFACEResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WEB_xmcml.ServiceReferenceLoadTasks.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WEB_xmcml.ServiceReferenceLoadTasks.Service1Soap>, WEB_xmcml.ServiceReferenceLoadTasks.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Init() {
            base.Channel.Init();
        }
        
        public int GetCurrentID() {
            return base.Channel.GetCurrentID();
        }
        
        public void ResetID() {
            base.Channel.ResetID();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceLoadTasks.GetIDNewTaskResponse WEB_xmcml.ServiceReferenceLoadTasks.Service1Soap.GetIDNewTask(WEB_xmcml.ServiceReferenceLoadTasks.GetIDNewTaskRequest request) {
            return base.Channel.GetIDNewTask(request);
        }
        
        public int GetIDNewTask(string taskName) {
            WEB_xmcml.ServiceReferenceLoadTasks.GetIDNewTaskRequest inValue = new WEB_xmcml.ServiceReferenceLoadTasks.GetIDNewTaskRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceLoadTasks.GetIDNewTaskRequestBody();
            inValue.Body.taskName = taskName;
            WEB_xmcml.ServiceReferenceLoadTasks.GetIDNewTaskResponse retVal = ((WEB_xmcml.ServiceReferenceLoadTasks.Service1Soap)(this)).GetIDNewTask(inValue);
            return retVal.Body.GetIDNewTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceLoadTasks.GetPathXMLResponse WEB_xmcml.ServiceReferenceLoadTasks.Service1Soap.GetPathXML(WEB_xmcml.ServiceReferenceLoadTasks.GetPathXMLRequest request) {
            return base.Channel.GetPathXML(request);
        }
        
        public string GetPathXML(int id) {
            WEB_xmcml.ServiceReferenceLoadTasks.GetPathXMLRequest inValue = new WEB_xmcml.ServiceReferenceLoadTasks.GetPathXMLRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceLoadTasks.GetPathXMLRequestBody();
            inValue.Body.id = id;
            WEB_xmcml.ServiceReferenceLoadTasks.GetPathXMLResponse retVal = ((WEB_xmcml.ServiceReferenceLoadTasks.Service1Soap)(this)).GetPathXML(inValue);
            return retVal.Body.GetPathXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceLoadTasks.GetPathSURFACEResponse WEB_xmcml.ServiceReferenceLoadTasks.Service1Soap.GetPathSURFACE(WEB_xmcml.ServiceReferenceLoadTasks.GetPathSURFACERequest request) {
            return base.Channel.GetPathSURFACE(request);
        }
        
        public string GetPathSURFACE(int id) {
            WEB_xmcml.ServiceReferenceLoadTasks.GetPathSURFACERequest inValue = new WEB_xmcml.ServiceReferenceLoadTasks.GetPathSURFACERequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceLoadTasks.GetPathSURFACERequestBody();
            inValue.Body.id = id;
            WEB_xmcml.ServiceReferenceLoadTasks.GetPathSURFACEResponse retVal = ((WEB_xmcml.ServiceReferenceLoadTasks.Service1Soap)(this)).GetPathSURFACE(inValue);
            return retVal.Body.GetPathSURFACEResult;
        }
    }
}
