//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_xmcml.ServiceReferenceControlTasks {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="WEB-xmcml", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="WEB-xmcml", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WEB-xmcml", ConfigurationName="ServiceReferenceControlTasks.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/Init", ReplyAction="*")]
        void Init();
        
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetNumTasks", ReplyAction="*")]
        int GetNumTasks();
        
        // CODEGEN: Generating message contract since element name GetTableStrResult from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetTableStr", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceControlTasks.GetTableStrResponse GetTableStr(WEB_xmcml.ServiceReferenceControlTasks.GetTableStrRequest request);
        
        // CODEGEN: Generating message contract since element name state from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetID", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceControlTasks.GetIDResponse GetID(WEB_xmcml.ServiceReferenceControlTasks.GetIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetPathDownloadOUTResult from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetPathDownloadOUT", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadOUTResponse GetPathDownloadOUT(WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadOUTRequest request);
        
        // CODEGEN: Generating message contract since element name GetPathDownloadMCMLResult from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetPathDownloadMCML", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadMCMLResponse GetPathDownloadMCML(WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadMCMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/DeleteTask", ReplyAction="*")]
        void DeleteTask(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableStr", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceControlTasks.GetTableStrRequestBody Body;
        
        public GetTableStrRequest() {
        }
        
        public GetTableStrRequest(WEB_xmcml.ServiceReferenceControlTasks.GetTableStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetTableStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int columnSort;
        
        public GetTableStrRequestBody() {
        }
        
        public GetTableStrRequestBody(int columnSort) {
            this.columnSort = columnSort;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableStrResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceControlTasks.GetTableStrResponseBody Body;
        
        public GetTableStrResponse() {
        }
        
        public GetTableStrResponse(WEB_xmcml.ServiceReferenceControlTasks.GetTableStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetTableStrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WEB_xmcml.ServiceReferenceControlTasks.ArrayOfString GetTableStrResult;
        
        public GetTableStrResponseBody() {
        }
        
        public GetTableStrResponseBody(WEB_xmcml.ServiceReferenceControlTasks.ArrayOfString GetTableStrResult) {
            this.GetTableStrResult = GetTableStrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetID", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceControlTasks.GetIDRequestBody Body;
        
        public GetIDRequest() {
        }
        
        public GetIDRequest(WEB_xmcml.ServiceReferenceControlTasks.GetIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string state;
        
        public GetIDRequestBody() {
        }
        
        public GetIDRequestBody(string state) {
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIDResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceControlTasks.GetIDResponseBody Body;
        
        public GetIDResponse() {
        }
        
        public GetIDResponse(WEB_xmcml.ServiceReferenceControlTasks.GetIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WEB_xmcml.ServiceReferenceControlTasks.ArrayOfInt GetIDResult;
        
        public GetIDResponseBody() {
        }
        
        public GetIDResponseBody(WEB_xmcml.ServiceReferenceControlTasks.ArrayOfInt GetIDResult) {
            this.GetIDResult = GetIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathDownloadOUTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathDownloadOUT", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadOUTRequestBody Body;
        
        public GetPathDownloadOUTRequest() {
        }
        
        public GetPathDownloadOUTRequest(WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadOUTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathDownloadOUTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetPathDownloadOUTRequestBody() {
        }
        
        public GetPathDownloadOUTRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathDownloadOUTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathDownloadOUTResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadOUTResponseBody Body;
        
        public GetPathDownloadOUTResponse() {
        }
        
        public GetPathDownloadOUTResponse(WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadOUTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathDownloadOUTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPathDownloadOUTResult;
        
        public GetPathDownloadOUTResponseBody() {
        }
        
        public GetPathDownloadOUTResponseBody(string GetPathDownloadOUTResult) {
            this.GetPathDownloadOUTResult = GetPathDownloadOUTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathDownloadMCMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathDownloadMCML", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadMCMLRequestBody Body;
        
        public GetPathDownloadMCMLRequest() {
        }
        
        public GetPathDownloadMCMLRequest(WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadMCMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathDownloadMCMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetPathDownloadMCMLRequestBody() {
        }
        
        public GetPathDownloadMCMLRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathDownloadMCMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathDownloadMCMLResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadMCMLResponseBody Body;
        
        public GetPathDownloadMCMLResponse() {
        }
        
        public GetPathDownloadMCMLResponse(WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadMCMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathDownloadMCMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPathDownloadMCMLResult;
        
        public GetPathDownloadMCMLResponseBody() {
        }
        
        public GetPathDownloadMCMLResponseBody(string GetPathDownloadMCMLResult) {
            this.GetPathDownloadMCMLResult = GetPathDownloadMCMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WEB_xmcml.ServiceReferenceControlTasks.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WEB_xmcml.ServiceReferenceControlTasks.Service1Soap>, WEB_xmcml.ServiceReferenceControlTasks.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Init() {
            base.Channel.Init();
        }
        
        public int GetNumTasks() {
            return base.Channel.GetNumTasks();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceControlTasks.GetTableStrResponse WEB_xmcml.ServiceReferenceControlTasks.Service1Soap.GetTableStr(WEB_xmcml.ServiceReferenceControlTasks.GetTableStrRequest request) {
            return base.Channel.GetTableStr(request);
        }
        
        public WEB_xmcml.ServiceReferenceControlTasks.ArrayOfString GetTableStr(int columnSort) {
            WEB_xmcml.ServiceReferenceControlTasks.GetTableStrRequest inValue = new WEB_xmcml.ServiceReferenceControlTasks.GetTableStrRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceControlTasks.GetTableStrRequestBody();
            inValue.Body.columnSort = columnSort;
            WEB_xmcml.ServiceReferenceControlTasks.GetTableStrResponse retVal = ((WEB_xmcml.ServiceReferenceControlTasks.Service1Soap)(this)).GetTableStr(inValue);
            return retVal.Body.GetTableStrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceControlTasks.GetIDResponse WEB_xmcml.ServiceReferenceControlTasks.Service1Soap.GetID(WEB_xmcml.ServiceReferenceControlTasks.GetIDRequest request) {
            return base.Channel.GetID(request);
        }
        
        public WEB_xmcml.ServiceReferenceControlTasks.ArrayOfInt GetID(string state) {
            WEB_xmcml.ServiceReferenceControlTasks.GetIDRequest inValue = new WEB_xmcml.ServiceReferenceControlTasks.GetIDRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceControlTasks.GetIDRequestBody();
            inValue.Body.state = state;
            WEB_xmcml.ServiceReferenceControlTasks.GetIDResponse retVal = ((WEB_xmcml.ServiceReferenceControlTasks.Service1Soap)(this)).GetID(inValue);
            return retVal.Body.GetIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadOUTResponse WEB_xmcml.ServiceReferenceControlTasks.Service1Soap.GetPathDownloadOUT(WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadOUTRequest request) {
            return base.Channel.GetPathDownloadOUT(request);
        }
        
        public string GetPathDownloadOUT(int id) {
            WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadOUTRequest inValue = new WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadOUTRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadOUTRequestBody();
            inValue.Body.id = id;
            WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadOUTResponse retVal = ((WEB_xmcml.ServiceReferenceControlTasks.Service1Soap)(this)).GetPathDownloadOUT(inValue);
            return retVal.Body.GetPathDownloadOUTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadMCMLResponse WEB_xmcml.ServiceReferenceControlTasks.Service1Soap.GetPathDownloadMCML(WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadMCMLRequest request) {
            return base.Channel.GetPathDownloadMCML(request);
        }
        
        public string GetPathDownloadMCML(int id) {
            WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadMCMLRequest inValue = new WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadMCMLRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadMCMLRequestBody();
            inValue.Body.id = id;
            WEB_xmcml.ServiceReferenceControlTasks.GetPathDownloadMCMLResponse retVal = ((WEB_xmcml.ServiceReferenceControlTasks.Service1Soap)(this)).GetPathDownloadMCML(inValue);
            return retVal.Body.GetPathDownloadMCMLResult;
        }
        
        public void DeleteTask(int id) {
            base.Channel.DeleteTask(id);
        }
    }
}
