//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_xmcml.ServiceReferenceSurfaceCreator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="WEB-xmcml", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WEB-xmcml", ConfigurationName="ServiceReferenceSurfaceCreator.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name centerX from namespace WEB-xmcml is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WEB-xmcml/GetPathSURFACEFile", ReplyAction="*")]
        WEB_xmcml.ServiceReferenceSurfaceCreator.GetPathSURFACEFileResponse GetPathSURFACEFile(WEB_xmcml.ServiceReferenceSurfaceCreator.GetPathSURFACEFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathSURFACEFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathSURFACEFile", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceSurfaceCreator.GetPathSURFACEFileRequestBody Body;
        
        public GetPathSURFACEFileRequest() {
        }
        
        public GetPathSURFACEFileRequest(WEB_xmcml.ServiceReferenceSurfaceCreator.GetPathSURFACEFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathSURFACEFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numSurfaces;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString centerX;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString centerY;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString centerZ;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString lengthX;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString lengthY;
        
        public GetPathSURFACEFileRequestBody() {
        }
        
        public GetPathSURFACEFileRequestBody(int numSurfaces, WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString centerX, WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString centerY, WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString centerZ, WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString lengthX, WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString lengthY) {
            this.numSurfaces = numSurfaces;
            this.centerX = centerX;
            this.centerY = centerY;
            this.centerZ = centerZ;
            this.lengthX = lengthX;
            this.lengthY = lengthY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPathSURFACEFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPathSURFACEFileResponse", Namespace="WEB-xmcml", Order=0)]
        public WEB_xmcml.ServiceReferenceSurfaceCreator.GetPathSURFACEFileResponseBody Body;
        
        public GetPathSURFACEFileResponse() {
        }
        
        public GetPathSURFACEFileResponse(WEB_xmcml.ServiceReferenceSurfaceCreator.GetPathSURFACEFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WEB-xmcml")]
    public partial class GetPathSURFACEFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPathSURFACEFileResult;
        
        public GetPathSURFACEFileResponseBody() {
        }
        
        public GetPathSURFACEFileResponseBody(string GetPathSURFACEFileResult) {
            this.GetPathSURFACEFileResult = GetPathSURFACEFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WEB_xmcml.ServiceReferenceSurfaceCreator.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WEB_xmcml.ServiceReferenceSurfaceCreator.Service1Soap>, WEB_xmcml.ServiceReferenceSurfaceCreator.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_xmcml.ServiceReferenceSurfaceCreator.GetPathSURFACEFileResponse WEB_xmcml.ServiceReferenceSurfaceCreator.Service1Soap.GetPathSURFACEFile(WEB_xmcml.ServiceReferenceSurfaceCreator.GetPathSURFACEFileRequest request) {
            return base.Channel.GetPathSURFACEFile(request);
        }
        
        public string GetPathSURFACEFile(int numSurfaces, WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString centerX, WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString centerY, WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString centerZ, WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString lengthX, WEB_xmcml.ServiceReferenceSurfaceCreator.ArrayOfString lengthY) {
            WEB_xmcml.ServiceReferenceSurfaceCreator.GetPathSURFACEFileRequest inValue = new WEB_xmcml.ServiceReferenceSurfaceCreator.GetPathSURFACEFileRequest();
            inValue.Body = new WEB_xmcml.ServiceReferenceSurfaceCreator.GetPathSURFACEFileRequestBody();
            inValue.Body.numSurfaces = numSurfaces;
            inValue.Body.centerX = centerX;
            inValue.Body.centerY = centerY;
            inValue.Body.centerZ = centerZ;
            inValue.Body.lengthX = lengthX;
            inValue.Body.lengthY = lengthY;
            WEB_xmcml.ServiceReferenceSurfaceCreator.GetPathSURFACEFileResponse retVal = ((WEB_xmcml.ServiceReferenceSurfaceCreator.Service1Soap)(this)).GetPathSURFACEFile(inValue);
            return retVal.Body.GetPathSURFACEFileResult;
        }
    }
}
